from pathlib import Path

path = Path(r"backend/main.py")
text = path.read_text()
old_block = "    if audio is not None:\n        try:\n            audio_suffix = os.path.splitext(audio.filename or \"\")[1] or \".webm\"\n            audio_temp = tempfile.NamedTemporaryFile(delete=False, suffix=audio_suffix)\n            temp_audio_path = audio_temp.name\n            audio_temp.close()\n            with open(temp_audio_path, \"wb\") as audio_buffer:\n                shutil.copyfileobj(audio.file, audio_buffer)\n            audio_received = True\n        except Exception as exc:\n            print(f\"Audio upload save failed: {exc}\")\n            cleanup_audio()\n            audio_received = False\n\n        try:\n            model = whisper.load_model(\"turbo\")\n            result = model.transcribe(temp_audio_path)\n            audio_transcript = (result.get(\"text\") or \"\").strip()\n        except Exception as exc:\n            print(f\"Audio transcription failed: {exc}\")\n        finally:\n            cleanup_audio()\n\n"
new_block = "    if audio is not None:\n        try:\n            audio_suffix = os.path.splitext(audio.filename or \"\")[1] or \".webm\"\n            audio_temp = tempfile.NamedTemporaryFile(delete=False, suffix=audio_suffix)\n            temp_audio_path = audio_temp.name\n            audio_temp.close()\n            with open(temp_audio_path, \"wb\") as audio_buffer:\n                shutil.copyfileobj(audio.file, audio_buffer)\n            audio_received = True\n        except Exception as exc:\n            print(f\"Audio upload save failed: {exc}\")\n            cleanup_audio()\n            audio_received = False\n\n        if temp_audio_path:\n            try:\n                model = whisper.load_model(\"turbo\")\n                result = model.transcribe(temp_audio_path)\n                audio_transcript = (result.get(\"text\") or \"\").strip()\n            except Exception as exc:\n                print(f\"Audio transcription failed: {exc}\")\n            finally:\n                cleanup_audio()\n\n"
if old_block not in text:
    raise SystemExit("Audio block not found for update")
text = text.replace(old_block, new_block, 1)
path.write_text(text)
